"""Second migrations

Revision ID: 02d4c3412d4f
Revises: b1073f0ca6cc
Create Date: 2022-11-03 17:39:29.226518

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '02d4c3412d4f'
down_revision = 'b1073f0ca6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
