"""Third migrations

Revision ID: 976d4dc6fbd3
Revises: 02d4c3412d4f
Create Date: 2022-11-03 17:40:44.865710

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '976d4dc6fbd3'
down_revision = '02d4c3412d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
